# 數據分析可以不要用迴圈 就不要用迴圈 是速度問題

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p = [1096.95, 596.95, 896.95]

In [3]:
c = 30.1

In [4]:
prices = np.array(p)

In [5]:
prices

array([1096.95,  596.95,  896.95])

In [6]:
print(prices)

[1096.95  596.95  896.95]


In [7]:
prices*c

array([33018.195, 17968.195, 26998.195])

# 這堂最重要的是 list 轉 array 去處理, 向量的處理方式