In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as pit

In [2]:
A = np.random.randn(100)

In [3]:
A

array([ 0.29649408, -0.32694652,  1.30752237,  1.35086631,  0.38030871,
       -0.46335567,  0.27467154,  1.64533097, -0.93462193,  1.01836039,
        0.72706563,  0.10998709, -0.27815801,  0.76931855,  0.40277473,
       -1.03225676,  0.77501078, -1.76700733,  1.65149767,  0.2655562 ,
        0.29598754,  0.61399075, -1.95453568, -0.43329602, -0.61313926,
        1.80836312, -0.00820335,  0.02787866,  2.16411053, -2.09484517,
        0.53631882,  0.79561047,  0.84605367, -0.81211514, -0.74936632,
       -0.77612592, -2.5202157 ,  0.23824464,  1.1463729 , -0.67044117,
       -0.72607401, -0.72843458, -1.09698117, -0.6065441 , -0.92861875,
        0.63638142,  0.57225018,  1.45925201,  0.09953834, -0.07003402,
       -1.01444401, -1.63967943, -0.94829933, -0.17674137, -0.47324352,
        0.8888967 ,  0.36914679,  0.5908811 ,  1.13209953,  0.82295138,
       -0.28270552,  0.30137903,  0.22325163, -2.46022485, -0.28481987,
       -0.66687147,  0.52342966, -0.2199461 ,  1.17787912, -0.14

In [4]:
A = 10*A + 50

In [5]:
A

array([52.96494075, 46.73053481, 63.07522366, 63.50866312, 53.80308709,
       45.36644334, 52.74671538, 66.45330974, 40.65378068, 60.1836039 ,
       57.27065627, 51.09987091, 47.21841992, 57.69318549, 54.02774725,
       39.67743237, 57.75010775, 32.32992673, 66.51497671, 52.65556201,
       52.95987538, 56.13990752, 30.45464318, 45.66703978, 43.86860736,
       68.08363122, 49.91796653, 50.27878662, 71.64110528, 29.05154827,
       55.36318817, 57.95610474, 58.46053675, 41.87884859, 42.50633684,
       42.23874083, 24.79784301, 52.38244644, 61.46372895, 43.29558826,
       42.73925988, 42.71565421, 39.03018826, 43.93455898, 40.71381251,
       56.36381422, 55.72250182, 64.59252014, 50.99538336, 49.29965985,
       39.8555599 , 33.6032057 , 40.51700671, 48.23258631, 45.26756483,
       58.88896696, 53.6914679 , 55.90881098, 61.32099535, 58.22951381,
       47.17294485, 53.01379034, 52.2325163 , 25.39775154, 47.1518013 ,
       43.33128528, 55.23429659, 47.80053902, 61.77879122, 48.54

In [6]:
A.shape

(100,)

In [7]:
A.shape = (5, 20)

In [8]:
A

array([[52.96494075, 46.73053481, 63.07522366, 63.50866312, 53.80308709,
        45.36644334, 52.74671538, 66.45330974, 40.65378068, 60.1836039 ,
        57.27065627, 51.09987091, 47.21841992, 57.69318549, 54.02774725,
        39.67743237, 57.75010775, 32.32992673, 66.51497671, 52.65556201],
       [52.95987538, 56.13990752, 30.45464318, 45.66703978, 43.86860736,
        68.08363122, 49.91796653, 50.27878662, 71.64110528, 29.05154827,
        55.36318817, 57.95610474, 58.46053675, 41.87884859, 42.50633684,
        42.23874083, 24.79784301, 52.38244644, 61.46372895, 43.29558826],
       [42.73925988, 42.71565421, 39.03018826, 43.93455898, 40.71381251,
        56.36381422, 55.72250182, 64.59252014, 50.99538336, 49.29965985,
        39.8555599 , 33.6032057 , 40.51700671, 48.23258631, 45.26756483,
        58.88896696, 53.6914679 , 55.90881098, 61.32099535, 58.22951381],
       [47.17294485, 53.01379034, 52.2325163 , 25.39775154, 47.1518013 ,
        43.33128528, 55.23429659, 47.80053902, 6

In [9]:
A.reshape(100, 1)

array([[52.96494075],
       [46.73053481],
       [63.07522366],
       [63.50866312],
       [53.80308709],
       [45.36644334],
       [52.74671538],
       [66.45330974],
       [40.65378068],
       [60.1836039 ],
       [57.27065627],
       [51.09987091],
       [47.21841992],
       [57.69318549],
       [54.02774725],
       [39.67743237],
       [57.75010775],
       [32.32992673],
       [66.51497671],
       [52.65556201],
       [52.95987538],
       [56.13990752],
       [30.45464318],
       [45.66703978],
       [43.86860736],
       [68.08363122],
       [49.91796653],
       [50.27878662],
       [71.64110528],
       [29.05154827],
       [55.36318817],
       [57.95610474],
       [58.46053675],
       [41.87884859],
       [42.50633684],
       [42.23874083],
       [24.79784301],
       [52.38244644],
       [61.46372895],
       [43.29558826],
       [42.73925988],
       [42.71565421],
       [39.03018826],
       [43.93455898],
       [40.71381251],
       [56

In [10]:
A

array([[52.96494075, 46.73053481, 63.07522366, 63.50866312, 53.80308709,
        45.36644334, 52.74671538, 66.45330974, 40.65378068, 60.1836039 ,
        57.27065627, 51.09987091, 47.21841992, 57.69318549, 54.02774725,
        39.67743237, 57.75010775, 32.32992673, 66.51497671, 52.65556201],
       [52.95987538, 56.13990752, 30.45464318, 45.66703978, 43.86860736,
        68.08363122, 49.91796653, 50.27878662, 71.64110528, 29.05154827,
        55.36318817, 57.95610474, 58.46053675, 41.87884859, 42.50633684,
        42.23874083, 24.79784301, 52.38244644, 61.46372895, 43.29558826],
       [42.73925988, 42.71565421, 39.03018826, 43.93455898, 40.71381251,
        56.36381422, 55.72250182, 64.59252014, 50.99538336, 49.29965985,
        39.8555599 , 33.6032057 , 40.51700671, 48.23258631, 45.26756483,
        58.88896696, 53.6914679 , 55.90881098, 61.32099535, 58.22951381],
       [47.17294485, 53.01379034, 52.2325163 , 25.39775154, 47.1518013 ,
        43.33128528, 55.23429659, 47.80053902, 6

# reshape 是產生一個新的 array 出來

In [11]:
A = A.reshape(100, 1)

In [12]:
A

array([[52.96494075],
       [46.73053481],
       [63.07522366],
       [63.50866312],
       [53.80308709],
       [45.36644334],
       [52.74671538],
       [66.45330974],
       [40.65378068],
       [60.1836039 ],
       [57.27065627],
       [51.09987091],
       [47.21841992],
       [57.69318549],
       [54.02774725],
       [39.67743237],
       [57.75010775],
       [32.32992673],
       [66.51497671],
       [52.65556201],
       [52.95987538],
       [56.13990752],
       [30.45464318],
       [45.66703978],
       [43.86860736],
       [68.08363122],
       [49.91796653],
       [50.27878662],
       [71.64110528],
       [29.05154827],
       [55.36318817],
       [57.95610474],
       [58.46053675],
       [41.87884859],
       [42.50633684],
       [42.23874083],
       [24.79784301],
       [52.38244644],
       [61.46372895],
       [43.29558826],
       [42.73925988],
       [42.71565421],
       [39.03018826],
       [43.93455898],
       [40.71381251],
       [56